Link js file. Add functions.
htmlacademy-javascript/287893-keksobooking-24 pull request #3
Opened 2021-09-25 16:14 UTC by Tanyakiss

Link js file. Add functions.

2021-09-26 09:08 UTC, Dima-Dim requested changes
Хорошо, но нужно доработать по замечаниям линтера.
https://github.com/htmlacademy-javascript/287893-keksobooking-24/pull/3/checks?check_run_id=3711814809

2021-09-26 09:08 UTC, Dima-Dim commented on js/main.js
> +  return ( +result.toFixed(numberRound) ); // с помощью + преобразую строку в число, т.к. toFixed возвращает string
При этом сама перепенная result не изменяется. так что её нужно объвлять через const.

2021-09-26 09:35 UTC, Tanyakiss commented on js/main.js
> +  return ( +result.toFixed(numberRound) ); // с помощью + преобразую строку в число, т.к. toFixed возвращает string
Ок. А что значит вот это "Process completed with exit code 1"?

2021-09-26 09:40 UTC, Tanyakiss commented on js/main.js
> +  return ( +result.toFixed(numberRound) ); // с помощью + преобразую строку в число, т.к. toFixed возвращает string
Все разобралась, про код выхода с ошибкой и без)

2021-09-26 09:46 UTC, Dima-Dim commented on js/main.js
> +  return ( +result.toFixed(numberRound) ); // с помощью + преобразую строку в число, т.к. toFixed возвращает string
Да, с такими вопросами отлично помогает Google :)

2021-09-26 09:47 UTC, Dima-Dim commented on js/main.js
> +  return ( +result.toFixed(numberRound) ); // с помощью + преобразую строку в число, т.к. toFixed возвращает string
Молодец что разобрался с этим ;)

2021-09-27 07:35 UTC, Dima-Dim commented on package.json
> +    "eslint": "^7.18.0",
На самом деле, так лучше не делать. Предсказуемость важнее.

2021-09-27 07:36 UTC, Dima-Dim approved these changes

2021-09-27 07:36 UTC, merged