Module4 task1
htmlacademy-javascript/287893-keksobooking-24 pull request #4
Opened 2021-10-05 08:03 UTC by Tanyakiss

Create array with 10 advertisement

2021-10-05 08:28 UTC, Dima-Dim requested changes
Хорошо, но можно лучше ;)

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +let offer = {
Почему let? Вопрос актуален для всех подобных let :)

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +  TITLE:[
https://up.htmlacademy.ru/javascript/24/criteries#b5
Актуально для всех массивов :)

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +    min:35.65000,
Похоже на константу https://up.htmlacademy.ru/javascript/24/criteries#b7

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +var createAdvertising = function (i){
Ну ладно let, var то нам зачем? За одно и не стрелочная функция нам тоже зачем?
А что такое i? :)

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +        location.lng],
Как-то не единообразно с `]` получилось.

2021-10-05 08:28 UTC, Dima-Dim commented on js/main.js
> +      avatar:'img/avatars/user' + (i < 10 ? '0' : '') + (i + 1) + '.png'
Давай использовать шаблонные строки для канкатинации.

2021-10-05 19:27 UTC, Dima-Dim requested changes
Хорошо. Теперь нужно решить конфликт на который указано здесь https://github.com/htmlacademy-javascript/287893-keksobooking-24/pull/4

2021-10-05 19:44 UTC, Tanyakiss commented
> Хорошо. Теперь нужно решить конфликт на который указано здесь #4

Вроде решила, но я не уверена)

2021-10-07 09:13 UTC, Tanyakiss commented
Не знаю, законно ли удалить все из ветки module4-tasck1 и записать в master

2021-10-08 05:13 UTC, Dima-Dim commented
> Не знаю, законно ли удалить все из ветки module4-tasck1 и записать в master

Думаю да, если ты можешь это сделать и оно решить твою проблему.

2021-10-08 06:00 UTC, Dima-Dim requested changes
Насколько я вижу https://github.com/htmlacademy-javascript/287893-keksobooking-24/pull/4/files сейчас ты пытаешься закомитить подключение lodash  и очистку файлов, которые ты до этого написала. Но у нас так делать не нужно :)

2021-10-08 18:05 UTC, merged